### PR TITLE
8308645: Javadoc of FFM API needs to be refreshed

### PR DESCRIPTION
**Pull request by mcimadamore**
This is the same PR as https://github.com/openjdk/jdk/pull/14098, but backported to the JDK 21 repo fork.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Change requires CSR request [JDK-8309553](https://bugs.openjdk.org/browse/JDK-8309553) to be approved
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8308645](https://bugs.openjdk.org/browse/JDK-8308645): Javadoc of FFM API needs to be refreshed (**Bug** - P3)
 * [JDK-8309398](https://bugs.openjdk.org/browse/JDK-8309398): ValueLayout:: arrayElementVarHandle doesn't throws UnsupportedOperationException - if byteAlignment() &gt; byteSize() (**Bug** - P3)
 * [JDK-8308812](https://bugs.openjdk.org/browse/JDK-8308812): SequenceLayout::withElementCount(long elementCount) doesn't throw IllegalArgumentException - if elementCount &lt; 0 for some cases (**Bug** - P3)
 * [JDK-8309553](https://bugs.openjdk.org/browse/JDK-8309553): Javadoc of FFM API needs to be refreshed (**CSR**)

### Reviewers
 * [Jorn Vernee](https://openjdk.org/census#jvernee) (@JornVernee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21.git pull/7/head:pull/7` \
`$ git checkout pull/7`

Update a local copy of the PR: \
`$ git checkout pull/7` \
`$ git pull https://git.openjdk.org/jdk21.git pull/7/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 7`

View PR using the GUI difftool: \
`$ git pr show -t 7`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21/pull/7.diff">https://git.openjdk.org/jdk21/pull/7.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21/pull/7#issuecomment-1587108475)

### CODE REVIEW

**Review by JornVernee — APPROVED** [review]
Already reviewed the other PR.

**Comment by JornVernee** [comment]
Btw, besides the other 2 issues this solves (from the other PR), I think this also solves: https://bugs.openjdk.org/browse/JDK-8255350

**Comment by mcimadamore** [comment]
> Btw, besides the other 2 issues this solves (from the other PR), I think this also solves: https://bugs.openjdk.org/browse/JDK-8255350

Thanks for the reminder - JDK-8255350 is not fixed by this, but by https://git.openjdk.org/jdk/pull/14007

**Comment by kevinrushforth** [comment]
@mcimadamore Shouldn't this go into the mainline first?

**Pull request closed without merging**
