### PR TITLE
8307858: [REDO] JDK-8307194 Add make target for optionally building a complete set of all JDK and hotspot libjvm static libraries

### PR DESCRIPTION
**Pull request by jianglizhou**
---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307858](https://bugs.openjdk.org/browse/JDK-8307858): [REDO] JDK-8307194 Add make target for optionally building a complete set of all JDK and hotspot libjvm static libraries (**Enhancement** - P4)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21.git pull/26/head:pull/26` \
`$ git checkout pull/26`

Update a local copy of the PR: \
`$ git checkout pull/26` \
`$ git pull https://git.openjdk.org/jdk21.git pull/26/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 26`

View PR using the GUI difftool: \
`$ git pr show -t 26`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21/pull/26.diff">https://git.openjdk.org/jdk21/pull/26.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21/pull/26#issuecomment-1595294903)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
As a P4 enhancement, this doesn't meet the criteria for integration into JDK 21 during [Rampdown Phase 1](https://mail.openjdk.org/pipermail/jdk-dev/2023-June/007911.html). You could request late approval to get this enhancement in, via the process described in [JEP 3](https://openjdk.org/jeps/3).

**Comment by jianglizhou** [comment]
> As a P4 enhancement, this doesn't meet the criteria for integration into JDK 21 during [Rampdown Phase 1](https://mail.openjdk.org/pipermail/jdk-dev/2023-June/007911.html). You could request late approval to get this enhancement in, via the process described in [JEP 3](https://openjdk.org/jeps/3).

Thanks for the pointer, @kevinrushforth. Will follow the process.

**Comment by dcubed-ojdk** [comment]
GHA is failing on windows; is this related to this PR or something else?

**Comment by dcubed-ojdk** [comment]
@erikj - You did a round of Mach5 testing on the JDK22 version of this fix. Do you
have plans to redo that testing for the JDK21 backport?

**Comment by jianglizhou** [comment]
> GHA is failing on windows; is this related to this PR or something else?

The windows build failures occur with other PRs as well, e.g. https://github.com/openjdk/jdk21/pull/24/checks?check_run_id=14317258603. The should be unrelated.

```
make: *** [jtdiff.gmk:36: D:/a/jdk21/jdk21/jtreg/src/build/classes.com.sun.javatest.diff.ok] Error 126
Error: Process completed with exit code 2.
```

I noticed these presubmit failures with `jdk` started since last week or so.

**Comment by erikj79** [comment]
> @erikj - You did a round of Mach5 testing on the JDK22 version of this fix. Do you have plans to redo that testing for the JDK21 backport?

I have done testing of the JDK 21 version of the patch and it's running cleanly.

**Comment by jianglizhou** [comment]
> > @erikj - You did a round of Mach5 testing on the JDK22 version of this fix. Do you have plans to redo that testing for the JDK21 backport?
> 
> I have done testing of the JDK 21 version of the patch and it's running cleanly.

Thanks for testing, @erikj79!

**Comment by jianglizhou** [comment]
> Since this Enhancement was rejected for JDK 21, this PR should be closed.

Closing without integration accordingly, thanks.

**Pull request closed without merging**
