### PR TITLE
8309032: jpackage does not work for module projects unless --module-path is specified

### PR DESCRIPTION
**Pull request by airsquared**
---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309032](https://bugs.openjdk.org/browse/JDK-8309032): jpackage does not work for module projects unless --module-path is specified (**Bug** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21.git pull/140/head:pull/140` \
`$ git checkout pull/140`

Update a local copy of the PR: \
`$ git checkout pull/140` \
`$ git pull https://git.openjdk.org/jdk21.git pull/140/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 140`

View PR using the GUI difftool: \
`$ git pr show -t 140`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21/pull/140.diff">https://git.openjdk.org/jdk21/pull/140.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21/pull/140#issuecomment-1643021651)

### CODE REVIEW

**Comment by AlanBateman** [comment]
JDK 21 is in rampdown phase two so only P1/P2 bugs (with approval) at this time, maybe this is one for JDK 21u instead.

**Comment by airsquared** [comment]
How likely is it that this can get approved in RDP 2? This is a only tiny change that fixes a bug in jpackage.

**Comment by AlanBateman** [comment]
> How likely is it that this can get approved in RDP 2? This is only a tiny change that fixes a minor bug in jpackage.

Unlikely as this is a P4 and not a regression in JDK 21. I think you should be aiming for jdk21u with this backport.

**Comment by airsquared** [comment]
I see. I'll create a PR there. Thanks.

**Comment by AlanBateman** [comment]
> I see. I'll create a PR there. Thanks.

Thanks, I assume this PR can be closed.

**Comment by airsquared** [comment]
Created openjdk/jdk21u#120.

**Pull request closed without merging**
