### PR TITLE
8310259: Pin msys2/setup-msys2 github action to a specific commit

### PR DESCRIPTION
**Pull request by jaikiran**
Can I please get a review of this change which backports the fixes for https://bugs.openjdk.org/browse/JDK-8310259?

This wasn't a clean backport because this also brings in https://bugs.openjdk.org/browse/JDK-8309934 which in theory isn't a must-have change, but I think it's good to have these changes match with what's in mainline.

With this commit in this PR, the windows github actions jobs that are failing in this jdk21 repo, should now continue to pass.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8310259](https://bugs.openjdk.org/browse/JDK-8310259): Pin msys2/setup-msys2 github action to a specific commit (**Task** - P4)
 * [JDK-8309934](https://bugs.openjdk.org/browse/JDK-8309934): Update GitHub Actions to use JDK 17 for building jtreg (**Bug** - P4)

### Reviewers
 * [Christian Stein](https://openjdk.org/census#cstein) (@sormuras - Committer)
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21.git pull/31/head:pull/31` \
`$ git checkout pull/31`

Update a local copy of the PR: \
`$ git checkout pull/31` \
`$ git pull https://git.openjdk.org/jdk21.git pull/31/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 31`

View PR using the GUI difftool: \
`$ git pr show -t 31`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21/pull/31.diff">https://git.openjdk.org/jdk21/pull/31.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21/pull/31#issuecomment-1597038106)

### CODE REVIEW

**Review by sormuras — APPROVED** [review]

**Comment by RealCLanger** [comment]
Could you then please also add the issue [JDK-8309934](https://bugs.openjdk.org/browse/JDK-8309934) to this PR?

**Comment by jaikiran** [comment]
Thank you Christian and Christoph for the reviews.

**Pull request closed without merging**
