### PR TITLE
8309258: RISC-V: Add riscv_hwprobe syscall

### PR DESCRIPTION
**Pull request by robehn**
Hi all,

This pull request contains a backport of commit [31b6fd77](https://github.com/openjdk/jdk/commit/31b6fd775f1c4f2841d9a52ad5f275ad446ee661) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Robbin Ehn on 20 Jun 2023 and was reviewed by Feilong Jiang, Thomas Stuefe, Fei Yang and Ludovic Henry.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309258](https://bugs.openjdk.org/browse/JDK-8309258): RISC-V: Add riscv_hwprobe syscall (**Enhancement** - P4)

### Reviewers
 * [Ludovic Henry](https://openjdk.org/census#luhenry) (@luhenry - Committer)
 * [Fei Yang](https://openjdk.org/census#fyang) (@RealFYang - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21.git pull/67/head:pull/67` \
`$ git checkout pull/67`

Update a local copy of the PR: \
`$ git checkout pull/67` \
`$ git pull https://git.openjdk.org/jdk21.git pull/67/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 67`

View PR using the GUI difftool: \
`$ git pr show -t 67`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21/pull/67.diff">https://git.openjdk.org/jdk21/pull/67.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21/pull/67#issuecomment-1608914017)

### CODE REVIEW

**Comment by robehn** [comment]
Late enhancement approved.
Applies clean, no additional review needed.

/integrate

**Comment by robehn** [comment]
@dholmes-ora or @JesperIRL do I need an actual review even when it applies clean ?
Or why can't I integrate?

**Comment by AlanBateman** [comment]
> @dholmes-ora or @JesperIRL do I need an actual review even when it applies clean ?
> Or why can't I integrate?

The process has changed for JDK 21 [1], the back port to the stabilization repo does need a Reviewer.

[1] https://mail.openjdk.org/pipermail/jdk-dev/2023-May/007889.html

**Comment by robehn** [comment]
> > @dholmes-ora or @JesperIRL do I need an actual review even when it applies clean ?
> > Or why can't I integrate?
> 
> The process has changed for JDK 21 [1], the back port to the stabilization repo does need a Reviewer.
> 
> [1] https://mail.openjdk.org/pipermail/jdk-dev/2023-May/007889.html

Thanks Alan!

**Review by luhenry — APPROVED** [review]

**Review by RealFYang — APPROVED** [review]

**Comment by robehn** [comment]
Thank!
/integrate

**Pull request closed without merging**
