### PR TITLE
8309862: Unsafe list operations in JfrStringPool

### PR DESCRIPTION
**Pull request by mgronlun**
---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8309862](https://bugs.openjdk.org/browse/JDK-8309862): Unsafe list operations in JfrStringPool (**Bug** - P2)

### Reviewers
 * [Erik Gahlin](https://openjdk.org/census#egahlin) (@egahlin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk21.git pull/12/head:pull/12` \
`$ git checkout pull/12`

Update a local copy of the PR: \
`$ git checkout pull/12` \
`$ git pull https://git.openjdk.org/jdk21.git pull/12/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 12`

View PR using the GUI difftool: \
`$ git pr show -t 12`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk21/pull/12.diff">https://git.openjdk.org/jdk21/pull/12.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk21/pull/12#issuecomment-1589171439)

### CODE REVIEW

**Comment by kevinrushforth** [comment]
@mgronlun This needs a Reviewer to approve.

**Comment by mgronlun** [comment]
> @mgronlun This needs a Reviewer to approve.

I thought a clean backport did not a review.

**Review by egahlin — APPROVED** [review]

**Comment by kevinrushforth** [comment]
> I thought a clean backport did not need a review. As described in https://wiki.openjdk.org/display/SKARA/Backports

That's true for backports to update releases. Backports to JDK feature release stabilization repos require review. See:

https://mail.openjdk.org/pipermail/jdk-dev/2023-April/007612.html

We should update the Wiki to reflect this.

**Comment by mgronlun** [comment]
> > I thought a clean backport did not need a review. As described in https://wiki.openjdk.org/display/SKARA/Backports
> 
> That's true for backports to update releases. Backports to JDK feature release stabilization repos require review. See:
> 
> https://mail.openjdk.org/pipermail/jdk-dev/2023-April/007612.html
> 
> We should update the Wiki to reflect this.

I see it was detailed in the Q and A. Thanks Kevin.

**Pull request closed without merging**
